[package]
name = "RSA-Implementation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibig = "0.3.6"
rand = "0.8"
mod_exp = "1.0.1"
druid = "0.7"
